CREATE TABLE IF NOT EXISTS model_themes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  model_id INT NOT NULL,
  theme_name VARCHAR(255) NOT NULL,
  primary_color VARCHAR(16) NOT NULL,
  secondary_color VARCHAR(16) NOT NULL,
  accent_color VARCHAR(16) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_model_themes_model (model_id),
  FOREIGN KEY (model_id) REFERENCES models(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


